version: '3.9'
services:
  mysql:
    build: mysql/
    networks:
      - app-net
    # hostname: mydb
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "mydb"
      
  app:
    image: shamir-repo:latest
    networks:
      - app-net
    depends_on:
      - mysql
  
  nginx:
    build: nginx/
    networks:
      - app-net
    ports:
    - "80:80"
    depends_on:
      - app

networks:
  app-net:
    name: app-net