version: '3.9'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "mydb"
    volumes:
      - mysql-vol:/var/lib/mysql
      - ./db/setup:/docker-entrypoint-initdb.d
    ports:
      - 8082:3306
      # - 8082:8082
      # - 3306:3306
  app:
    build: .
    ports:
      - 8081:5000


volumes:
  mysql-vol: