version: '3.9'
services:
  mysql:
    image: mysql:latest
    networks:
      - app-net
    # hostname: mydb
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "mydb"
    volumes:
      - mysql-vol:/var/lib/mysql
      - ./db/setup:/docker-entrypoint-initdb.d
    ports:
      # - 8080:8080
      - 8082:3306
      # - 8082:8082
      # - 3306:3306
  app:
    image: shamir-repo:latest
    networks:
      - app-net
    ports:
      - 8081:5000
    depends_on:
      - mysql
  
  nginx:
    image: nginx
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-net
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=flask-app
    - NGINX_PORT=5000
    depends_on:
      - app

networks:
  app-net:
    name: app-net
    # Use a custom driver
    # driver: custom-driver-1

volumes:
  mysql-vol: